### ISSUE TITLE
C-Extension build problems

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-package-handling#55]
I am trying to build conda-package-handling for our internal Conda distribution, the the `archive_utils_cy` seem to be broken. I've tried linking cph dynamically against a "normal" libarchive (as in the libarchive-feedstock as well as statically against a _libarchive_for_cph.

Libarchive itself seems to work (at least the bundled `bsdtar` command does), but I cannot create archives using `conda_package_handling.arcive_utils_cy.create_archive()`.  It always returns an error and the error message is just a few bytes of gibberish that cannot be decoded into a string (I tried ascii, latin1 and utf-8 encoding).

I tried it on fedora 29, centos 7 (only the dynamically linked version) and centos8.  We use the system gcc and libc, but bzip2, zlib, xz, lz4 and zstd are conda packages.  I used these recipes for _libarchive_for_cph and conda-package-handling (condensed to the minium for linux builds):

### libarchive (static)
```yaml
{% set version = '3.3.3' %}
{% set sha256 = 'ba7eb1781c9fbbae178c4c6bad1c6eb08edab9a1496c64833d1715d022b30e2e' %}
package:
  name: _libarchive_static_for_cph
  version: {{ version }}

source:
  url: https://github.com/libarchive/libarchive/releases/download/v{{ version }}/libarchive-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - 0002-xar-fix-bad-seek-in-move_reading_point.patch

build:
  number: 0
  missing_dso_whitelist:
    - '*/libc.so.6'
    - '*/libdl.so.2'
    - '*/libm.so.6'

requirements:
  build:
    - bzip2
    - zlib
    - zstd
  run:
    - bzip2
    - zlib
    - zstd

test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"  # [unix]
    - test -f "${PREFIX}/include/archive.h"            # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"      # [unix]
    - test -f "${PREFIX}/lib/libarchive.a"             # [unix]
    - test -f "${PREFIX}/lib/libarchive_and_deps.a"    # [unix]
```
```sh
export CFLAGS="${CFLAGS} -fPIC"

autoreconf -vfi
mkdir build-conda && pushd build-conda
../configure --prefix=${PREFIX}     \
             --enable-static        \
             --with-bz2lib          \
             --with-iconv           \
             --with-zlib            \
             --with-zstd            \
             --disable-bsdcat       \
             --disable-bsdcpio      \
             --disable-bsdtar       \
             --disable-shared       \
             --without-cng          \
             --without-expat        \
             --without-lz4          \
             --without-lzma         \
             --without-lzo2         \
             --without-nettle       \
             --without-openssl      \
             --without-xml2
make -j${CPU_COUNT}
make install-strip
popd

# remove the man pages
rm -rf ${PREFIX}/share/man

# create libarchive_and_deps.a
if [[ "$(uname)" == Linux ]]; then
    pushd ${PREFIX}/lib
    ar -M <<EOM
        CREATE libarchive_and_deps.a
        ADDLIB libarchive.a
        ADDLIB libbz2.a
        ADDLIB libz.a
        ADDLIB libzstd.a
        SAVE
        END
EOM
    ranlib libarchive_and_deps.a
    popd
fi
```

### conda-package-handling
```yaml
{% set version = '1.6.0' %}
{% set sha256 = '7afeb4adeeba2f6cfafe37f93ebe1c15983e4f8e4e868de3dd58b35b456b800e' %}

package:
  name: conda-package-handling
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-handling/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  entry_points:
    - cph = conda_package_handling.cli:main

build:
  number: 2
  missing_dso_whitelist:
    - '*/libc.so.6'
    - '*/libpthread.so.0'

requirements:
  build:
    - python
    - pip
    - cython
    - _libarchive_static_for_cph

  run:
    - python
    - six
    - tqdm

test:
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  commands:
    - cph --help
    - cph create . test.tar.bz2; test -f test.tar.bz2; cph extract test.tar.bz2
```
```sh
export CFLAGS="$CFLAGS -I$PREFIX/include -fPIC"
# export LDFLAGS="$LDFLAGS -L$PREFIX/lib -Wl,-no-export-dynamic -static -static-libgcc"
# $PYTHON setup.py build_ext -i
$PYTHON -m pip install -I --no-deps .
```
